
a = []
a.append(input("Enter noun "))
a.append(input("Enter noun "))
a.append(input("Enter noun "))
a.append(input("Enter noun "))
a.append(input("Enter ing verb "))
a.append(input("Enter ing verb "))
a.append(input("Enter ing verb "))
a.append(input("Enter ing verb "))
a.append(input("Enter an adjective "))
a.append(input("Enter an adjective "))
a.append(input("Enter an adjective "))

print("Today is Monday")
print("I have to get ready to go to %s" % a[0])
print("so I started %s." % a[1])
print("When I got to %s" % a[0])
print("I saw %s %s" % (a[2], a[0]))
print("and I felt %s knowing where I was." % a[2])
print("I was %s inside" % a[1])
print("and started %s around." % a[1])
print("I then started %s" % a[1])
print("back to my %s %s" % (a[2], a[0]))
