print("Today is Monday")

verb1 = input("Enter an 'ing' verb ")
adjective = input("Enter an adjective ")
noun1 = input("Enter an noun ")
verb2 = input("Enter an 'ing' verb ")
noun2 = input("Enter an noun ")
verb3 = input("Enter an 'ing' verb ")
adjective2 = input("Enter an adjective ")
noun3 = input("Enter an noun ")
adjective3 = input("Enter an adjective ")
noun4 = input("Enter and noun ")
print("I have to get ready to go to %s" % noun1)
print("so I started %s." % verb1)
print("When I got to %s" % noun2)
print("I saw %s" % (adjective, noun3))
print("and I felt %s knowing where I was." % adjective2)
print("I was %s inside" % verb2)
print("and started %s around.")
print("I then started %s" % verb3)
print("back to my %s %s" % (adjective3, noun4))
